# Generated by Django 5.0.3 on 2024-05-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_second',
            field=models.BooleanField(default=False),
        ),
    ]
