# Generated by Django 5.0.3 on 2025-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_first',
            new_name='is_all',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_second',
            new_name='is_side',
        ),
        migrations.AddField(
            model_name='post',
            name='is_home',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
