# Generated by Django 5.0.3 on 2024-04-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_estimate_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
