# Generated by Django 5.0.3 on 2025-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
