# Generated by Django 5.0.3 on 2025-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0005_alter_estimate_name_alter_estimate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
