# Generated by Django 5.0.3 on 2025-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0006_estimate_is_public_estimate_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmyungHanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='번호')),
                ('pron', models.CharField(max_length=10, verbose_name='발음')),
                ('char', models.CharField(max_length=10, verbose_name='한자')),
                ('main_mean', models.CharField(max_length=100, verbose_name='뜻')),
                ('tot_stk', models.IntegerField(verbose_name='전체획수')),
                ('main_elem', models.CharField(max_length=10, verbose_name='한자오행')),
                ('disused', models.BooleanField(default=False, verbose_name='불용한자')),
                ('rad_stk', models.IntegerField(verbose_name='부수획수')),
                ('rad', models.CharField(max_length=10, verbose_name='부수한자')),
                ('rad_elem', models.CharField(max_length=10, verbose_name='부수오행')),
                ('detail_mean', models.TextField(verbose_name='세부뜻')),
                ('meaning', models.CharField(max_length=100, verbose_name='의미발음')),
                ('stk_info', models.CharField(max_length=50, verbose_name='획수정보')),
                ('rad_id', models.IntegerField(verbose_name='부수번호')),
                ('no_rad_stk', models.IntegerField(verbose_name='부수제외획수')),
                ('rad_mean', models.CharField(max_length=100, verbose_name='부수뜻')),
            ],
        ),
    ]
