# Generated by Django 5.0.3 on 2025-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0008_estimate_name_hanja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='gen',
            field=models.CharField(max_length=10),
        ),
    ]
