# Generated by Django 5.0.3 on 2025-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0009_alter_estimate_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='is_public',
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
