# Generated by Django 5.0.3 on 2024-03-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrdg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manseryuk',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manseryuk',
            name='month',
            field=models.IntegerField(default=4),
        ),
    ]
