# Generated by Django 5.0.3 on 2024-04-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrdg', '0002_alter_manseryuk_day_alter_manseryuk_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manseryuk',
            name='day',
            field=models.IntegerField(default=2),
        ),
    ]
