# Generated by Django 5.0.3 on 2024-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrdg', '0005_alter_manseryuk_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manseryuk',
            name='day',
            field=models.IntegerField(default=11),
        ),
    ]
