# Generated by Django 5.0.3 on 2025-05-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrdg', '0007_remove_manseryuk_time_manseryuk_hour_manseryuk_min_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manseryuk',
        ),
    ]
