# Generated by Django 5.0.3 on 2024-04-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_alter_submit_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submit',
            name='visit',
            field=models.CharField(blank=True, choices=[('visit', '방문상담'), ('email', '메일상담'), ('call', '전화상담')], max_length=20),
        ),
    ]
