# Generated by Django 5.0.3 on 2024-03-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_manseryuk_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manseryuk',
        ),
    ]
