# Generated by Django 5.0.3 on 2024-04-30 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_delete_manseryuk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('data', models.JSONField(default=dict)),
                ('gen', models.CharField(blank=True, max_length=1)),
                ('sl', models.CharField(blank=True, max_length=10)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('month', models.CharField(blank=True, max_length=2)),
                ('day', models.CharField(blank=True, max_length=2)),
                ('hour', models.CharField(blank=True, max_length=2)),
                ('min', models.CharField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
