# Generated by Django 5.0.3 on 2024-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
