# Generated by Django 5.0.3 on 2024-05-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_bgimg_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
