# Generated by Django 5.0.3 on 2024-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customboard_customcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customboard',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customcomment',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
