# Generated by Django 5.0.3 on 2024-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_customboard_email_alter_customcomment_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
