# Generated by Django 5.0.3 on 2024-05-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_pageview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageview',
            old_name='views',
            new_name='total_views',
        ),
        migrations.CreateModel(
            name='PageViewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('page_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pageview')),
            ],
            options={
                'unique_together': {('page_view', 'date')},
            },
        ),
    ]
