# Generated by Django 5.0.3 on 2025-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_views_pageview_total_views_pageviewdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
