# Generated by Django 5.0.3 on 2025-05-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_profile_bgimg_alter_profile_picture'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pageviewdetail',
        #     name='page_view',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='pageviewdetail',
        #     unique_together=None,
        # ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='PageViewDetail',
        ),
    ]
