# Generated by Django 5.0.3 on 2025-06-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_pageviewdetail_page_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customboard',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
