# Generated by Django 5.0.3 on 2025-05-18 21:28

from django.db import migrations

def delete_pageview_tables(apps, schema_editor):
    schema_editor.delete_model(apps.get_model('base', 'PageView'))
    schema_editor.delete_model(apps.get_model('base', 'PageViewDetail'))

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_pageviewdetail_page_view_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_pageview_tables),
    ]
