# Generated by Django 5.0.3 on 2025-06-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_customboard_is_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=10, verbose_name='작성자 이름')),
                ('post_title', models.CharField(max_length=200, verbose_name='게시글 제목')),
                ('post_is_secret', models.BooleanField(default=False, verbose_name='비공개 여부')),
                ('post_password', models.CharField(default='0632857255', max_length=20, verbose_name='게시글 비밀번호')),
                ('post_content', models.TextField(verbose_name='게시글 내용')),
                ('comment_content', models.TextField(verbose_name='댓글 내용')),
                ('comment_publish_delay_minutes', models.PositiveIntegerField(default=60, help_text='게시글이 발행된 후 몇 분 뒤에 댓글을 등록할지 설정합니다.', verbose_name='댓글 발행 지연(분)')),
                ('status', models.CharField(choices=[('PENDING', '발행 대기'), ('POST_PUBLISHED', '글 발행 완료'), ('ALL_PUBLISHED', '전체 발행 완료'), ('ERROR', '오류')], db_index=True, default='PENDING', max_length=20)),
                ('post_published_at', models.DateTimeField(blank=True, null=True, verbose_name='글 발행 시각')),
                ('published_board', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customboard')),
                ('published_comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customcomment')),
            ],
            options={
                'verbose_name': '예약 발행 아이템',
                'verbose_name_plural': '예약 발행 아이템 목록',
                'ordering': ['id'],
            },
        ),
    ]
