# Generated by Django 5.0.3 on 2024-03-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manseryuk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manseryuk',
        ),
    ]
