# Generated by Django 5.0.3 on 2024-03-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manseryuk', '0003_manseryuk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manseryuk',
        ),
    ]
